### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by chron0** [AbeEstrada/atom-remember-window#3]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details

```
Package.activateConfig (/usr/local/share/atom/resources/app.asar/src/package.js:265:11)
Package.activateNow (/usr/local/share/atom/resources/app.asar/src/package.js:236:14)
<unknown> (/usr/local/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/local/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/local/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/local/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

**Comment by AbeEstrada** [comment]
This package is not required anymore to make Atom remember your window position, this feature was added a few versions ago and you can uninstall it and Atom will remember your window position by default. I unpublished this package 10 months ago. I'm not going to update it because now it's not necessary.

**Comment by chron0** [comment]
Oh, great, I just clicked the "report issue" button in atom and didn't realize they had that feature already integrated in mainline :) So thanks for releasing this helper and the heads up.
